flags:
 language-c-quote:
   full-haskell-antiquotes: false
extra-package-dbs: []
packages:
- '.'
- '../isa-parser'
extra-deps:
- alex-3.2.3
- happy-1.19.9
- haskell-exp-parser-0.1.1
- sbv-7.8
- GHood-0.0.7
- crackNum-2.2
- FloatingHex-0.4
- pretty-show-ansi-wl-1.9.2
resolver: lts-12.20
allow-newer: true
package-indices:
  - name: HackageOrig
    download-prefix: https://hackage.haskell.org/package/
    http: https://hackage.haskell.org/01-index.tar.gz
