flags: {}
extra-package-dbs: []
packages:
- '.'
- '../isa-parser'
extra-deps:
- alex-3.2.3
- happy-1.19.9
- disassembler-0.2.0.1
- flippers-1.0.1
- hscurses-1.4.2.0
resolver: lts-11.9
allow-newer: true
